2024-02-06 12:32:08,949 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-06 12:32:08,949 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Configure stats pid to 761840
2024-02-06 12:32:08,949 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Loading settings from /user/gent/457/vsc45787/.config/wandb/settings
2024-02-06 12:32:08,949 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Loading settings from /kyukon/home/gent/457/vsc45787/bsc/Centralized_controller/wandb/settings
2024-02-06 12:32:08,949 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-06 12:32:08,950 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-06 12:32:08,950 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-06 12:32:08,950 INFO    MainThread:761840 [wandb_init.py:_log_setup():526] Logging user logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized_controller/wandb/run-20240206_123208-egocshiz/logs/debug.log
2024-02-06 12:32:08,950 INFO    MainThread:761840 [wandb_init.py:_log_setup():527] Logging internal logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized_controller/wandb/run-20240206_123208-egocshiz/logs/debug-internal.log
2024-02-06 12:32:08,950 INFO    MainThread:761840 [wandb_init.py:init():566] calling init triggers
2024-02-06 12:32:08,950 INFO    MainThread:761840 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'nn_architecture': [30, 128, 128, 20], 'activation_function': 'Tanh', 'num_generations': 2500, 'es_popsize': 300}
2024-02-06 12:32:08,950 INFO    MainThread:761840 [wandb_init.py:init():616] starting backend
2024-02-06 12:32:08,950 INFO    MainThread:761840 [wandb_init.py:init():620] setting up manager
2024-02-06 12:32:09,008 ERROR   MainThread:761840 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2024-02-06 12:32:16,979 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-06 12:32:16,979 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Configure stats pid to 761840
2024-02-06 12:32:16,979 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Loading settings from /user/gent/457/vsc45787/.config/wandb/settings
2024-02-06 12:32:16,979 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Loading settings from /kyukon/home/gent/457/vsc45787/bsc/Centralized_controller/wandb/settings
2024-02-06 12:32:16,980 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-06 12:32:16,980 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-06 12:32:16,980 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-06 12:32:16,980 INFO    MainThread:761840 [wandb_init.py:_log_setup():526] Logging user logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized_controller/wandb/run-20240206_123216-updjvrtr/logs/debug.log
2024-02-06 12:32:16,980 INFO    MainThread:761840 [wandb_init.py:_log_setup():527] Logging internal logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized_controller/wandb/run-20240206_123216-updjvrtr/logs/debug-internal.log
2024-02-06 12:32:16,980 INFO    MainThread:761840 [wandb_init.py:init():566] calling init triggers
2024-02-06 12:32:16,980 INFO    MainThread:761840 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'nn_architecture': [30, 128, 128, 20], 'activation_function': 'Tanh', 'num_generations': 2500, 'es_popsize': 300}
2024-02-06 12:32:16,980 INFO    MainThread:761840 [wandb_init.py:init():616] starting backend
2024-02-06 12:32:16,981 INFO    MainThread:761840 [wandb_init.py:init():620] setting up manager
2024-02-06 12:32:17,003 ERROR   MainThread:761840 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2024-02-06 12:32:47,889 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-06 12:32:47,889 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Configure stats pid to 761840
2024-02-06 12:32:47,889 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Loading settings from /user/gent/457/vsc45787/.config/wandb/settings
2024-02-06 12:32:47,889 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Loading settings from /kyukon/home/gent/457/vsc45787/bsc/Centralized_controller/wandb/settings
2024-02-06 12:32:47,890 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-06 12:32:47,890 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-06 12:32:47,890 INFO    MainThread:761840 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-06 12:32:47,890 INFO    MainThread:761840 [wandb_init.py:_log_setup():526] Logging user logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized_controller/wandb/run-20240206_123247-c58gvl6m/logs/debug.log
2024-02-06 12:32:47,890 INFO    MainThread:761840 [wandb_init.py:_log_setup():527] Logging internal logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized_controller/wandb/run-20240206_123247-c58gvl6m/logs/debug-internal.log
2024-02-06 12:32:47,890 INFO    MainThread:761840 [wandb_init.py:init():566] calling init triggers
2024-02-06 12:32:47,890 INFO    MainThread:761840 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'nn_architecture': [30, 128, 128, 20], 'activation_function': 'Tanh', 'num_generations': 2500, 'es_popsize': 300}
2024-02-06 12:32:47,890 INFO    MainThread:761840 [wandb_init.py:init():616] starting backend
2024-02-06 12:32:47,890 INFO    MainThread:761840 [wandb_init.py:init():620] setting up manager
2024-02-06 12:32:47,913 ERROR   MainThread:761840 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/user/gent/457/vsc45787/.conda/envs/hope/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
